### ISSUE TITLE
Enhancement suggestion for application.yaml in Utilisateur Service

### ISSUE THREAD

**Issue by YacoubBen7amama** [projet-d-innovation/delib-backend#10]
I would like to suggest two enhancements to the application.yaml file in the Utilisateur Service.

Firstly, we have previously agreed that the application name should end with "-service" for consistency with our naming convention. Therefore, I suggest updating the "spring.application.name" property to reflect this.

Secondly, I noticed that the profile "dev" is explicitly mentioned in the "spring.profiles.active" property. As we typically default to the "dev" profile during development, I suggest removing this property to simplify the configuration.

**Comment by Elbouchouki** [comment]
Application name in Utilisateur Service will be changed.
you should not change the application.yaml.(idk what do you mean by simplifying the configuration)
