### ISSUE TITLE
User Service -  Adding/Removing Users To department

### ISSUE THREAD

**Issue by YacoubBen7amama** [projet-d-innovation/delib-backend#27]
Adding a user to a department in the Department Service does not check if the user exists in the database of user Service. 
To add a user, the endpoints ` PUT \   /api/v1/departements/{codeDepartement}/utilisateur/{codeUser}` or `DELETE\ 
 /api/v1/departements/{codeDepartement}/utilisateur/bulk` with a list of users ID can be used. Additionally, removing a user from a department checks if the user exists in your  database and if they are a chef departement or filiere. This means that you need to change their role before deleting them. Patching requests can be used for this.

**Comment by oaymn** [comment]
This is doe not relate to our application design.
Please refer to the application design and read the implementation before opening issues.
