### ISSUE TITLE
Annee Universitaire - Issues with Service Name and Adding/Removing Année for Filiere

### ISSUE THREAD

**Issue by YacoubBen7amama** [projet-d-innovation/delib-backend#28]
The service name for the Annee Universitaire service should be `annee-universitaire-service`.
Additionally, to add an anneeUniversitaire ID to a Filiere, the endpoint ` PUT \     /api/v1/filieres/{codeFiliere}/anneeUniversitaire/{codeAnnee}` can be used. However, this endpoint does not check if the code is already being used by your database, so you need to check if there is such an anneeUniver with such an ID. 
To remove an Annee from a Filiere, the endpoint `DELETE\   /api/v1/filieres/{codeFiliere}/anneeUniversitaire/{codeAnnee}`  , but for this time it will check if the Id exist in AnneeUnversitaire database .

**Comment by oaymn** [comment]
- The `Annee Universitaire` is yet to be implemented.
- Issues should not be created for non-existing parts of the application
- Suggestions about the parts that are yet to be implemented should be discussed during the meetings.
