### ISSUE TITLE
Module Service -  Adding/Removing a Module to/from a Semestre

### ISSUE THREAD

**Issue by YacoubBen7amama** [projet-d-innovation/delib-backend#29]
To add a module to a semestre, the endpoint `PUT\   /api/v1/semestres/{codeSemestre}/module/{codeModule}` can be used. However, this endpoint does not check if the code is already being used by the database in module service , so you need to check if there is such a module with such an ID. 
To remove a module from a semestre, the endpoint `DELETE\  /api/v1/semestres/{codeSemestre}/module/{codeModule}` can be used.

**Comment by YacoubBen7amama** [comment]
min kandwiw 3la relation mabin semestre o module , ah 3arfin f module kayn wa7d l key ki refers to semestre , wlkin ila bchina l semestre ach nahomaa les modules 3ndha ? 
hadchi 3lach kayna wa7d liste f semestre smitha modulesids fiha ga3 les keys .
hadok 2 endpoint ki ajoutiw ou bien ki removiw

**Comment by YacoubBen7amama** [comment]
had lblan kan galo bouchouki

**Comment by YacoubBen7amama** [comment]
ila knti ba4i codesemestre o t searchi f module  bach tfetchihom hadi hadra 5ra

**Comment by oaymn** [comment]
- `Semestre` does not need to have refs to the modules that belongs to it since we can get them by providing `codeSemestre` to the `Module` service. In fact we discussed that on the last meeting and it should be implemented by the next push.

> had lblan kan galo bouchouki

perhaps @Elbouchouki can clarify things

**Comment by YacoubBen7amama** [comment]
achban lk 7seen  tbchi les utilisateurs o tfetchi les etudiants based on the filiere ids li f annee universitaire or tbchi l filiere o tfetchihom , ach ban lk ?
finma tb4i tlisti les etudiants lif filiere sir dir wa7d requete sql lifiha where filieres= (binathmon annee universitaire) o dirha 3la wa7d data base utilisateur ((prof +admin + student) + o fetchi roles )

**Comment by YacoubBen7amama** [comment]
[https://github.com/projet-d-innovation/delib-backend/blob/a4de12c1f46a5dbe3ca40e9e2b1b3ed791290437/utilisateur-service/src/main/java/ma/enset/utilisateur/model/Utilisateur.java#L49](url)
check this , hadi raha deja tpushat

**Comment by YacoubBen7amama** [comment]
https://github.com/projet-d-innovation/delib-backend/blob/a4de12c1f46a5dbe3ca40e9e2b1b3ed791290437/utilisateur-service/src/main/java/ma/enset/utilisateur/model/Utilisateur.java#L44
check this link , hadchi rah dar lih pull request

**Comment by YacoubBen7amama** [comment]
f utilisateur kayna une liste diak les elementIds

**Comment by Elbouchouki** [comment]
@YacoubBen7amama , galik "we discussed that on the last meeting and it should be implemented by the next push".
 https://github.com/projet-d-innovation/delib-backend/blob/d7186a7dda84ddb7fe0e87b98d0a8af1d01d1613/utilisateur-service/src/main/java/ma/enset/utilisateur/model/Utilisateur.java#L45

**Comment by oaymn** [comment]
> achban lk 7seen tbchi les utilisateurs ola tfetchi les etudiants based on the filiere ids li f annee universitaire or tbchi l filiere o tfetchihom , ach ban lk ? finma tb4i tlisti les etudiants lif filiere sir dir wa7d requete sql lifiha where filieres= (binathmon annee universitaire) o dirha 3la wa7d data base utilisateur ((prof +admin + student) + o fetchi roles )

Even though the `Session Universitaire` service which handles `Session Universitaire` and `Année Universitaire` hasn't been implemented yet but here's how it will be: 
You send a GET request to the service in which you include `codeFiliere`, and `année` and you'll get as a response a list of students that match that.
I have to say this again all of this has been discussed during the last meeting.

**Comment by oaymn** [comment]
> @YacoubBen7amama , galik "we discussed that on the last meeting and it should be implemented by the next push".
> 
> https://github.com/projet-d-innovation/delib-backend/blob/d7186a7dda84ddb7fe0e87b98d0a8af1d01d1613/utilisateur-service/src/main/java/ma/enset/utilisateur/model/Utilisateur.java#L45

I believe this should be part of a DTO not the model

**Comment by Elbouchouki** [comment]
> > @YacoubBen7amama , galik "we discussed that on the last meeting and it should be implemented by the next push".
> > https://github.com/projet-d-innovation/delib-backend/blob/d7186a7dda84ddb7fe0e87b98d0a8af1d01d1613/utilisateur-service/src/main/java/ma/enset/utilisateur/model/Utilisateur.java#L45
> 
> I believe this should be part of a DTO not the model

The mapping typically happens in the controller layer. If you want to include a list of elements in the DTO, you will need to pass the mapping to the service layer. this will take a lot of refactoring.

**Comment by oaymn** [comment]
I see, the time constraints does not allow for that at the moment.
