### ISSUE TITLE
Session Service- Issues with Adding/Removing a Session to/from a Semestre

### ISSUE THREAD

**Issue by YacoubBen7amama** [projet-d-innovation/delib-backend#30]
To add a session to a semestre, the endpoint `PUT\  /api/v1/semestres/{codeSemestre}/session/{codeSession}` can be used. However, this endpoint does not check if the code is already being used by the database in session service , so you need to check if  there is such a session with such an ID.
To remove a session from a semestre, the endpoint `DELETE\  /api/v1/semestres/{codeSemestre}/session/{codeSession}` can be used.

**Comment by oaymn** [comment]
The `Session` microservice is yet to be implemented, so basically the issue is pointing to a non-exisiting service.

**Comment by YacoubBen7amama** [comment]
kandon drt @documentation

**Comment by oaymn** [comment]
`@documentation` is used for additions or suggesting improvements to the documentation.
In our case there is no documentation to start with.

**Comment by YacoubBen7amama** [comment]
ok , daba imagini ba4i chi endpoint nzidha f filiere , ba4iha nta f module , kifach 4adi tgolha lia ?

ana fkit had issues b @doc ob @enhancement bach lbnadem lichadhom ijri m3aya , soit service t9ad ou bien mat9adch

**Comment by oaymn** [comment]
`Filiere` already exists, in that case I would use the `@enhancement`  to respond to your question. Session does is yet to be implemented it shoud be on the backlog.
