### ISSUE TITLE
Semestre service - Retrieving multiple semesters using their codes

### ISSUE THREAD

**Issue by oaymn** [projet-d-innovation/delib-backend#31]
We need the ability to retrieve a list of semseters by providing their codes.
It's needed for when the module service needs to check the existance of those semesters during bulk save.

**Comment by YacoubBen7amama** [comment]
received

**Comment by oaymn** [comment]
Please feel free to close this issue when it's implemented.

**Comment by oaymn** [comment]
Issues should not be closed unless the fix is merged or the issue is invalid.
