### ISSUE TITLE
Retrieving users by username

### ISSUE THREAD

**Issue by zakaria-root** [projet-d-innovation/delib-backend#34]
We need the ability to retrieve all the users by their names.
It is necessary when we want to search for a user by his name in the Frontend.

**Comment by Elbouchouki** [comment]
Let's prioritize the main functionalities we discussed in our last meeting for now, and leave other functionalities such as search and sort for later. Once these are implemented, I will close this issue.

**Comment by Elbouchouki** [comment]
Closed in favor of #50
