### ISSUE TITLE
Error when starting Utilisateur service due to missing table

### ISSUE THREAD

**Issue by YacoubBen7amama** [projet-d-innovation/delib-backend#9]
After filling the application properties, I attempted to start the service, but it failed due to a database error. The issue seems to be related to the "utilisateur.Role" table, as it appears to be missing when the  seeder tries to fill data into database . Below is the error message:

`2023-04-21T23:31:38.343Z ERROR 6272 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table 'Utilisateur.role' doesn't exist
2023-04-21T23:31:38.343Z  INFO 6272 --- [           main] o.h.e.internal.DefaultLoadEventListener  : HHH000327: Error performing load command`
`......`
`at ma.enset.utilisateur.util.DatabaseSeeder.run(DatabaseSeeder.java:93) ~[classes/:na]`
`.......`
`at ma.enset.utilisateur.UtilisateurApplication.main(UtilisateurApplication.java:11) ~[classes/:na]`
`Caused by: java.sql.SQLSyntaxErrorException: Table 'Utilisateur.role' doesn't exist`
`........`
`2023-04-21T23:31:41.405Z  INFO 6272 --- [           main] com.netflix.discovery.DiscoveryClient    : Unregistering ...
2023-04-21T23:31:41.418Z  INFO 6272 --- [           main] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UTILISATEUR/LEGION5.mshome.net:utilisateur:8080 - deregister  status: 200
2023-04-21T23:31:41.421Z  INFO 6272 --- [           main] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient`

**Comment by Elbouchouki** [comment]
It's normal to have this exception because, JPA is trying to delete previous tables so it can create new ones, and because there no tables that exists, it throws an exception. however the service starts without any problems.
(I've already discussed this with aymane , and he agreed that it's fine)

**Comment by YacoubBen7amama** [comment]
Although it may be working well for you, we need to find a solution that works for us. Therefore, it's on  yours to come up with a way to fix the issue. 
( I have had no issues with  Aymane's module service  )
